server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
  #注册到zookeeper地址
    zookeeper:
      connect-string: 10.0.45.193:2181
  logging:
    level:
      # feign日志以什么级别监控哪个接口
      com.atguigu.springcloud.service.PaymentFeignService: debug

